
[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[general]

import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]
shell = "/usr/bin/fish"

