theme = "kanagawa-dragon"

[editor]
line-number = "relative"
cursorline = true
mouse = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

