theme = "monokai_aqua"

[editor]
cursorline = true
end-of-line-diagnostics = "hint"
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

