-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local mocha = require("mocha")

--###############

--## MONITORS ###

--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
	output   = "DP-3",
	mode     = "3840x2160@144",
	position = "auto",
	scale    = 1.5,
})

hl.monitor({
	output   = "DP-2",
	mode     = "3840x2160@144",
	position = "auto-left",
	scale    = 1.5,
})

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use

local terminal = "ghostty"

local fileManager = "dolphin"

local browser = "brave"

--############################

--## ENVIRONMENT VARIABLES ###

--############################

hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)
hl.env("HYPRCURSOR_SIZE", 28)
hl.env("HYPRCURSOR_THEME", "catppuccin-mocha-dark-cursors")

hl.env("QT_QPA_PLATFORM", "wayland")

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

hl.env("XDG_MENU_PREFIX", "arch-")

--################

--## AUTOSTART ###

--################

-- workaround for being unable to copy paste between wayland and x11 apps

-- exec-once = wl-paste -t text -w bash -c '[ "$(xclip -selection clipboard -o)" = "$(wl-paste -n)" ] || [ "$(wl-paste -l | grep image)" = "" ] && xclip -selection clipboard'

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
	general = {
		gaps_in = 2,
		gaps_out = 4,
		border_size = 2,
		col = {
			-- active_border = mocha.lavender,
			active_border = "rgb(b4befe)",
			inactive_border = "rgba(595959aa)",
		},
		resize_on_border = true,
		allow_tearing = false,
		layout = "dwindle",
	},

	decoration = {
		rounding = 0,
		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			range = 4,
			render_power = 3,
			color = "rgba(1a1a1aee)",
		},
		-- https://wiki.hyprland.org/Configuring/Variables/#blur
		blur = {
			enabled = true,
			size = 3,
			passes = 1,
			vibrancy = 0.1696,
		},
	},

	animations = {
		enabled = false,
	},
})

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

-- hl.config({
-- 	dwindle = {
-- 		pseudotile = true,
-- 		-- Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
-- 		preserve_split = true,
-- 		-- You probably want this
-- 	},
-- })

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
	master = {
		new_status = "master",
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
	misc = {
		-- Set to 0 or 1 to disable the anime mascot wallpapers
		force_default_wallpaper = false,
		-- If true disables the random hyprland logo / anime girl background. :(
		disable_hyprland_logo = true,
	},
})

--############

--## INPUT ###

--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",
		repeat_rate = 50,
		follow_mouse = 1,
		sensitivity = 0,
		-- -1.0 - 1.0, 0 means no modification.
		touchpad = {
			natural_scroll = false,
		},
	},
})

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Sets "Windows" key as main modifier
local mainMod = "SUPER"

local shiftMod = "SHIFT+SUPER"

local altMod = "SUPER+ALT"

hl.bind("CTRL+SUPER+ALT" .. " + " .. "R", hl.dsp.exec_cmd("hyprctl reload; systemctl --user restart waybar.service"),
	{ repeating = true })

-- allow my push to talk button to always work
-- hl.bind("Control_L", hl.dsp.pass("class:^(discord)$"))

-- lock, logout, reboot, shutdown bar
hl.bind(mainMod .. " + " .. "ESCAPE", hl.dsp.exec_cmd("nwg-bar -t custom_bar.json"))

-- fullscreen cover top bar
hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

-- fullscreen but more like a maximize
hl.bind(mainMod .. " + " .. "D", hl.dsp.window.fullscreen())

-- two launcher binds because I want to be able to use it with either one, left or right
hl.bind("SUPER" .. " + " .. "SUPER_L",
	hl.dsp.exec_cmd("pkill wofi || uwsm app -- $(wofi --allow-images --show drun --define=drun-print_desktop_file=true)"),
	{ repeating = true })
hl.bind("SUPER" .. " + " .. "SUPER_R",
	hl.dsp.exec_cmd("pkill wofi || uwsm app -- $(wofi --allow-images --show drun --define=drun-print_desktop_file=true)"),
	{ repeating = true })

-- launch terminal
hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("uwsm app -- " .. terminal))

-- close current window
hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

-- screenshots / snips
-- select a window
hl.bind(shiftMod .. " + " .. "PRINT", hl.dsp.exec_cmd("hyprshot -m window --freeze"))

-- select a monitor
hl.bind("PRINT", hl.dsp.exec_cmd("hyprshot -m output --freeze"))

-- select a region
hl.bind(mainMod .. " + " .. "PRINT", hl.dsp.exec_cmd("hyprshot -m region --freeze"))

-- launch browser
hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("uwsm app -- " .. browser))

-- lock
hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("uwsm app -- hyprlock"))

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("uwsm stop"))

-- open file explorer
hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("uwsm app -- " .. fileManager))

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())
hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- Move focus with alt+mainMod + vim keys
hl.bind(altMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }), { repeating = true })
hl.bind(altMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }), { repeating = true })
hl.bind(altMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }), { repeating = true })
hl.bind(altMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }), { repeating = true })

-- move window shift+mod + vim keys
hl.bind(shiftMod .. " + " .. "H", hl.dsp.window.move({ direction = "l" }))
hl.bind(shiftMod .. " + " .. "L", hl.dsp.window.move({ direction = "r" }))
hl.bind(shiftMod .. " + " .. "K", hl.dsp.window.move({ direction = "u" }))
hl.bind(shiftMod .. " + " .. "J", hl.dsp.window.move({ direction = "d" }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true })

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

hl.window_rule({
	name           = "supress-maximize-requests-from-apps",
	match          = {
		class = ".*",
	},
	suppress_event = "maximize",
})

hl.window_rule({
	name     = "fix-xwayland-drags",
	match    = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},
	no_focus = true,
})

hl.workspace_rule({
	workspace = 1,
	monitor = "DP-2",
	default = true,
})

hl.workspace_rule({
	workspace = 2,
	monitor = "DP-2",
})

hl.workspace_rule({
	workspace = 3,
	monitor = "DP-2",
})

hl.workspace_rule({
	workspace = 4,
	monitor = "DP-2",
})

hl.workspace_rule({
	workspace = 5,
	monitor = "DP-2",
})

hl.workspace_rule({
	workspace = 6,
	monitor = "DP-3",
	default = true,
})

hl.workspace_rule({
	workspace = 7,
	monitor = "DP-3",
})

hl.workspace_rule({
	workspace = 8,
	monitor = "DP-3",
})

hl.workspace_rule({
	workspace = 9,
	monitor = "DP-3",
})

hl.workspace_rule({
	workspace = 10,
	monitor = "DP-3",
})

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme catppuccin-mocha-dark-cursors")
	hl.exec_cmd("udiskie")
	hl.exec_cmd("input-remapper-control --command autoload")
end)
